# Generated by Django 3.2.9 on 2022-04-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20220425_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_user_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='create_user_number_limit',
            field=models.IntegerField(null=True),
        ),
    ]
