# Generated by Django 3.2.9 on 2022-04-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20220425_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_user_number_limit',
            field=models.IntegerField(default=0),
        ),
    ]
