# Generated by Django 3.2.9 on 2022-04-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_user_create_user_number_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_export',
            field=models.BooleanField(default=False),
        ),
    ]
