# Generated by Django 3.2.9 on 2022-04-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_user_can_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_read_answer',
            field=models.BooleanField(default=True),
        ),
    ]
