# Generated by Django 3.2.9 on 2022-05-09 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcement', '0004_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendshipLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(default=True)),
                ('order', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friendship_links',
                'ordering': ('-order',),
            },
        ),
    ]
