# Generated by Django 3.2.9 on 2022-05-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0006_auto_20220509_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='verify',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='verify',
            field=models.BooleanField(default=True),
        ),
    ]
