# Generated by Django 3.2.9 on 2022-05-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_auto_20220425_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='submit_limit',
            field=models.IntegerField(default=0),
        ),
    ]
