# Generated by Django 3.2.9 on 2022-05-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0016_problemanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemtag',
            options={'ordering': ('-order',)},
        ),
        migrations.AddField(
            model_name='problemtag',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
