# Generated by Django 3.2.9 on 2022-05-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0017_auto_20220509_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemanswer',
            name='verify',
            field=models.BooleanField(default=True),
        ),
    ]
